### CONSTANTS USED IN NAVIGATION ###
VISUALISATION = False
PROXIMITY_RADIUS = 30 # in centimeters

### CONSTANTS USED IN GUIDE ###
STEP_LENGTH = 40 # in centimeters
USER_SPEED = 0.4 # in m/s
STAIR_LIMIT = 25
ORIENTATION_DEGREE_ERROR = 20
INSTRUCTIONS_FREQUENCY = 60 # in seconds
MAX_ON_PLATFORM_STEPS = 15 #counts

